export default [
  {id: 'ac-story', dungeon: 'Ascalonian Catacombs', name: 'Story', path: 0, level: 30, rewards: {gold: 2600, goldDaily: 0, tokens: 0, tokensDaily: 0}},
  {id: 'hodgins', dungeon: 'Ascalonian Catacombs', name: 'Hodgins', path: 1, level: 35, rewards: {gold: 2600, goldDaily: 5000, tokens: 20, tokensDaily: 80}},
  {id: 'detha', dungeon: 'Ascalonian Catacombs', name: 'Detha', path: 2, level: 35, rewards: {gold: 2600, goldDaily: 5000, tokens: 20, tokensDaily: 80}},
  {id: 'tzark', dungeon: 'Ascalonian Catacombs', name: 'Tzark', path: 3, level: 35, rewards: {gold: 2600, goldDaily: 5000, tokens: 20, tokensDaily: 80}},
  {id: 'cm-story', dungeon: 'Caudecus\'s Manor', name: 'Story', path: 0, level: 40, rewards: {gold: 2600, goldDaily: 0, tokens: 0, tokensDaily: 0}},
  {id: 'asura', dungeon: 'Caudecus\'s Manor', name: 'Asura', path: 1, level: 45, rewards: {gold: 2600, goldDaily: 3500, tokens: 20, tokensDaily: 80}},
  {id: 'seraph', dungeon: 'Caudecus\'s Manor', name: 'Seraph', path: 2, level: 45, rewards: {gold: 2600, goldDaily: 3500, tokens: 20, tokensDaily: 80}},
  {id: 'butler', dungeon: 'Caudecus\'s Manor', name: 'Butler', path: 3, level: 45, rewards: {gold: 2600, goldDaily: 3500, tokens: 20, tokensDaily: 80}},
  {id: 'ta-story', dungeon: 'Twilight Arbor', name: 'Story', path: 0, level: 50, rewards: {gold: 2600, goldDaily: 0, tokens: 0, tokensDaily: 0}},
  {id: 'vevina', dungeon: 'Twilight Arbor', name: 'Vevina (Forward)', path: 1, level: 55, rewards: {gold: 2600, goldDaily: 3500, tokens: 20, tokensDaily: 80}},
  {id: 'leurent', dungeon: 'Twilight Arbor', name: 'Leurent (Up)', path: 3, level: 55, rewards: {gold: 2600, goldDaily: 3500, tokens: 20, tokensDaily: 80}},
  {id: 'aetherpath', dungeon: 'Twilight Arbor', name: 'Aetherpath', path: 4, level: 80, rewards: {gold: 2600, goldDaily: 6600, tokens: 20, tokensDaily: 80}},
  {id: 'se-story', dungeon: 'Sorrow\'s Embrace', name: 'Story', path: 0, level: 60, rewards: {gold: 2600, goldDaily: 0, tokens: 0, tokensDaily: 0}},
  {id: 'fergg', dungeon: 'Sorrow\'s Embrace', name: 'Fergg', path: 1, level: 65, rewards: {gold: 2600, goldDaily: 3500, tokens: 20, tokensDaily: 80}},
  {id: 'rasalov', dungeon: 'Sorrow\'s Embrace', name: 'Rasolov', path: 2, level: 65, rewards: {gold: 2600, goldDaily: 3500, tokens: 20, tokensDaily: 80}},
  {id: 'koptev', dungeon: 'Sorrow\'s Embrace', name: 'Koptev', path: 3, level: 65, rewards: {gold: 2600, goldDaily: 3500, tokens: 20, tokensDaily: 80}},
  {id: 'cof-story', dungeon: 'Citadel of Flame', name: 'Story', path: 0, level: 70, rewards: {gold: 2600, goldDaily: 0, tokens: 0, tokensDaily: 0}},
  {id: 'ferrah', dungeon: 'Citadel of Flame', name: 'Ferrah', path: 1, level: 75, rewards: {gold: 2600, goldDaily: 3500, tokens: 20, tokensDaily: 80}},
  {id: 'magg', dungeon: 'Citadel of Flame', name: 'Magg', path: 2, level: 75, rewards: {gold: 2600, goldDaily: 3500, tokens: 20, tokensDaily: 80}},
  {id: 'rhiannon', dungeon: 'Citadel of Flame', name: 'Rhiannon', path: 3, level: 75, rewards: {gold: 2600, goldDaily: 3500, tokens: 20, tokensDaily: 80}},
  {id: 'hotw-story', dungeon: 'Honor of the Waves', name: 'Story', path: 0, level: 76, rewards: {gold: 2600, goldDaily: 0, tokens: 0, tokensDaily: 0}},
  {id: 'butcher', dungeon: 'Honor of the Waves', name: 'Butcher', path: 1, level: 80, rewards: {gold: 2600, goldDaily: 3500, tokens: 20, tokensDaily: 80}},
  {id: 'plunderer', dungeon: 'Honor of the Waves', name: 'Plunderer', path: 2, level: 80, rewards: {gold: 2600, goldDaily: 3500, tokens: 20, tokensDaily: 80}},
  {id: 'zealot', dungeon: 'Honor of the Waves', name: 'Zealot', path: 3, level: 80, rewards: {gold: 2600, goldDaily: 3500, tokens: 20, tokensDaily: 80}},
  {id: 'coe-story', dungeon: 'Crucible of Eternity', name: 'Story', path: 0, level: 78, rewards: {gold: 2600, goldDaily: 0, tokens: 0, tokensDaily: 0}},
  {id: 'submarine', dungeon: 'Crucible of Eternity', name: 'Submarine', path: 1, level: 80, rewards: {gold: 2600, goldDaily: 3500, tokens: 20, tokensDaily: 80}},
  {id: 'teleporter', dungeon: 'Crucible of Eternity', name: 'Teleporter', path: 2, level: 80, rewards: {gold: 2600, goldDaily: 3500, tokens: 20, tokensDaily: 80}},
  {id: 'front_door', dungeon: 'Crucible of Eternity', name: 'Front Door', path: 3, level: 80, rewards: {gold: 2600, goldDaily: 3500, tokens: 20, tokensDaily: 80}},
  {id: 'arah-story', dungeon: 'The Ruined City of Arah', name: 'Story', path: 0, level: 80, rewards: {gold: 2600, goldDaily: 0, tokens: 0, tokensDaily: 0}},
  {id: 'jotun', dungeon: 'The Ruined City of Arah', name: 'Jotun', path: 1, level: 80, rewards: {gold: 2600, goldDaily: 10000, tokens: 20, tokensDaily: 80}},
  {id: 'mursaat', dungeon: 'The Ruined City of Arah', name: 'Mursaat', path: 2, level: 80, rewards: {gold: 2600, goldDaily: 10500, tokens: 20, tokensDaily: 80}},
  {id: 'forgotten', dungeon: 'The Ruined City of Arah', name: 'Forgotten', path: 3, level: 80, rewards: {gold: 2600, goldDaily: 15500, tokens: 20, tokensDaily: 80}},
  {id: 'seer', dungeon: 'The Ruined City of Arah', name: 'Seer', path: 4, level: 80, rewards: {gold: 2600, goldDaily: 10000, tokens: 20, tokensDaily: 80}}
]
