export default [
  {id: 'ac_story', dungeon: 'Ascalonian Catacombs', name: 'Story', path: 0, frequenterIndex: 4, level: 30, rewards: {gold: 2600, goldDaily: 0, tokens: 0, tokensDaily: 0}},
  {id: 'hodgins', dungeon: 'Ascalonian Catacombs', name: 'Hodgins', path: 1, frequenterIndex: 5, level: 35, rewards: {gold: 2600, goldDaily: 5000, tokens: 20, tokensDaily: 80}},
  {id: 'detha', dungeon: 'Ascalonian Catacombs', name: 'Detha', path: 2, frequenterIndex: 6, level: 35, rewards: {gold: 2600, goldDaily: 5000, tokens: 20, tokensDaily: 80}},
  {id: 'tzark', dungeon: 'Ascalonian Catacombs', name: 'Tzark', path: 3, frequenterIndex: 7, level: 35, rewards: {gold: 2600, goldDaily: 5000, tokens: 20, tokensDaily: 80}},
  {id: 'cm_story', dungeon: 'Caudecus\'s Manor', name: 'Story', path: 0, frequenterIndex: 12, level: 40, rewards: {gold: 2600, goldDaily: 0, tokens: 0, tokensDaily: 0}},
  {id: 'asura', dungeon: 'Caudecus\'s Manor', name: 'Asura', path: 1, frequenterIndex: 13, level: 45, rewards: {gold: 2600, goldDaily: 3500, tokens: 20, tokensDaily: 80}},
  {id: 'seraph', dungeon: 'Caudecus\'s Manor', name: 'Seraph', path: 2, frequenterIndex: 14, level: 45, rewards: {gold: 2600, goldDaily: 3500, tokens: 20, tokensDaily: 80}},
  {id: 'butler', dungeon: 'Caudecus\'s Manor', name: 'Butler', path: 3, frequenterIndex: 15, level: 45, rewards: {gold: 2600, goldDaily: 3500, tokens: 20, tokensDaily: 80}},
  {id: 'ta_story', dungeon: 'Twilight Arbor', name: 'Story', path: 0, frequenterIndex: 20, level: 50, rewards: {gold: 2600, goldDaily: 0, tokens: 0, tokensDaily: 0}},
  {id: 'vevina', dungeon: 'Twilight Arbor', name: 'Vevina (Forward)', path: 1, frequenterIndex: 22, level: 55, rewards: {gold: 2600, goldDaily: 3500, tokens: 20, tokensDaily: 80}},
  {id: 'leurent', dungeon: 'Twilight Arbor', name: 'Leurent (Up)', path: 3, frequenterIndex: 21, level: 55, rewards: {gold: 2600, goldDaily: 3500, tokens: 20, tokensDaily: 80}},
  {id: 'aetherpath', dungeon: 'Twilight Arbor', name: 'Aetherpath', path: 4, frequenterIndex: 23, level: 80, rewards: {gold: 2600, goldDaily: 6600, tokens: 20, tokensDaily: 80}},
  {id: 'se_story', dungeon: 'Sorrow\'s Embrace', name: 'Story', path: 0, frequenterIndex: 16, level: 60, rewards: {gold: 2600, goldDaily: 0, tokens: 0, tokensDaily: 0}},
  {id: 'fergg', dungeon: 'Sorrow\'s Embrace', name: 'Fergg', path: 1, frequenterIndex: 17, level: 65, rewards: {gold: 2600, goldDaily: 3500, tokens: 20, tokensDaily: 80}},
  {id: 'rasalov', dungeon: 'Sorrow\'s Embrace', name: 'Rasolov', path: 2, frequenterIndex: 18, level: 65, rewards: {gold: 2600, goldDaily: 3500, tokens: 20, tokensDaily: 80}},
  {id: 'koptev', dungeon: 'Sorrow\'s Embrace', name: 'Koptev', path: 3, frequenterIndex: 19, level: 65, rewards: {gold: 2600, goldDaily: 3500, tokens: 20, tokensDaily: 80}},
  {id: 'cof_story', dungeon: 'Citadel of Flame', name: 'Story', path: 0, frequenterIndex: 28, level: 70, rewards: {gold: 2600, goldDaily: 0, tokens: 0, tokensDaily: 0}},
  {id: 'ferrah', dungeon: 'Citadel of Flame', name: 'Ferrah', path: 1, frequenterIndex: 29, level: 75, rewards: {gold: 2600, goldDaily: 3500, tokens: 20, tokensDaily: 80}},
  {id: 'magg', dungeon: 'Citadel of Flame', name: 'Magg', path: 2, frequenterIndex: 30, level: 75, rewards: {gold: 2600, goldDaily: 3500, tokens: 20, tokensDaily: 80}},
  {id: 'rhiannon', dungeon: 'Citadel of Flame', name: 'Rhiannon', path: 3, frequenterIndex: 31, level: 75, rewards: {gold: 2600, goldDaily: 3500, tokens: 20, tokensDaily: 80}},
  {id: 'hotw_story', dungeon: 'Honor of the Waves', name: 'Story', path: 0, frequenterIndex: 24, level: 76, rewards: {gold: 2600, goldDaily: 0, tokens: 0, tokensDaily: 0}},
  {id: 'butcher', dungeon: 'Honor of the Waves', name: 'Butcher', path: 1, frequenterIndex: 25, level: 80, rewards: {gold: 2600, goldDaily: 3500, tokens: 20, tokensDaily: 80}},
  {id: 'plunderer', dungeon: 'Honor of the Waves', name: 'Plunderer', path: 2, frequenterIndex: 26, level: 80, rewards: {gold: 2600, goldDaily: 3500, tokens: 20, tokensDaily: 80}},
  {id: 'zealot', dungeon: 'Honor of the Waves', name: 'Zealot', path: 3, frequenterIndex: 27, level: 80, rewards: {gold: 2600, goldDaily: 3500, tokens: 20, tokensDaily: 80}},
  {id: 'coe_story', dungeon: 'Crucible of Eternity', name: 'Story', path: 0, frequenterIndex: 0, level: 78, rewards: {gold: 2600, goldDaily: 0, tokens: 0, tokensDaily: 0}},
  {id: 'submarine', dungeon: 'Crucible of Eternity', name: 'Submarine', path: 1, frequenterIndex: 1, level: 80, rewards: {gold: 2600, goldDaily: 3500, tokens: 20, tokensDaily: 80}},
  {id: 'teleporter', dungeon: 'Crucible of Eternity', name: 'Teleporter', path: 2, frequenterIndex: 2, level: 80, rewards: {gold: 2600, goldDaily: 3500, tokens: 20, tokensDaily: 80}},
  {id: 'front_door', dungeon: 'Crucible of Eternity', name: 'Front Door', path: 3, frequenterIndex: 3, level: 80, rewards: {gold: 2600, goldDaily: 3500, tokens: 20, tokensDaily: 80}},
  {id: 'arah_story', dungeon: 'The Ruined City of Arah', name: 'Story', path: 0, frequenterIndex: -1, level: 80, rewards: {gold: 2600, goldDaily: 0, tokens: 0, tokensDaily: 0}},
  {id: 'jotun', dungeon: 'The Ruined City of Arah', name: 'Jotun', path: 1, frequenterIndex: 8, level: 80, rewards: {gold: 2600, goldDaily: 10000, tokens: 20, tokensDaily: 80}},
  {id: 'mursaat', dungeon: 'The Ruined City of Arah', name: 'Mursaat', path: 2, frequenterIndex: 9, level: 80, rewards: {gold: 2600, goldDaily: 10500, tokens: 20, tokensDaily: 80}},
  {id: 'forgotten', dungeon: 'The Ruined City of Arah', name: 'Forgotten', path: 3, frequenterIndex: 10, level: 80, rewards: {gold: 2600, goldDaily: 15500, tokens: 20, tokensDaily: 80}},
  {id: 'seer', dungeon: 'The Ruined City of Arah', name: 'Seer', path: 4, frequenterIndex: 11, level: 80, rewards: {gold: 2600, goldDaily: 10000, tokens: 20, tokensDaily: 80}}
]
