module.exports = [
  {level: 1, fractal: 'Urban Battleground', ar: 0, relics: 5},
  {level: 2, fractal: 'Swampland', ar: 0, relics: 5},
  {level: 3, fractal: 'Aquatic Ruins', ar: 0, relics: 5},
  {level: 4, fractal: 'Uncategorized', ar: 0, relics: 5},
  {level: 5, fractal: 'Snowblind', ar: 0, relics: 5},
  {level: 6, fractal: 'Volcanic', ar: 0, relics: 6},
  {level: 7, fractal: 'Cliffside', ar: 0, relics: 6},
  {level: 8, fractal: 'Underground Facility', ar: 0, relics: 6},
  {level: 9, fractal: 'Molten Furnace', ar: 0, relics: 6},
  {level: 10, fractal: 'Molten Boss', ar: 0, relics: 6},
  {level: 11, fractal: 'Urban Battleground', ar: 0, relics: 7},
  {level: 12, fractal: 'Uncategorized', ar: 0, relics: 7},
  {level: 13, fractal: 'Chaos Isles', ar: 0, relics: 7},
  {level: 14, fractal: 'Aetherblade', ar: 0, relics: 7},
  {level: 15, fractal: 'Thaumanova Reactor', ar: 0, relics: 7},
  {level: 16, fractal: 'Snowblind', ar: 0, relics: 8},
  {level: 17, fractal: 'Underground Facility', ar: 0, relics: 8},
  {level: 18, fractal: 'Captain Mai Trin Boss', ar: 0, relics: 8},
  {level: 19, fractal: 'Volcanic', ar: 0, relics: 8},
  {level: 20, fractal: 'Solid Ocean', ar: 8, relics: 8},
  {level: 21, fractal: 'Swampland', ar: 10, relics: 9},
  {level: 22, fractal: 'Cliffside', ar: 11, relics: 9},
  {level: 23, fractal: 'Molten Furnace', ar: 13, relics: 9},
  {level: 24, fractal: 'Aetherblade', ar: 15, relics: 9},
  {level: 25, fractal: 'Nightmare', ar: 17, relics: 9},
  {level: 26, fractal: 'Aquatic Ruins', ar: 18, relics: 10},
  {level: 27, fractal: 'Snowblind', ar: 20, relics: 10},
  {level: 28, fractal: 'Volcanic', ar: 22, relics: 10},
  {level: 29, fractal: 'Underground Facility', ar: 24, relics: 10},
  {level: 30, fractal: 'Chaos Isles', ar: 26, relics: 10},
  {level: 31, fractal: 'Urban Battleground', ar: 27, relics: 11},
  {level: 32, fractal: 'Swampland', ar: 29, relics: 11},
  {level: 33, fractal: 'Cliffside', ar: 31, relics: 11},
  {level: 34, fractal: 'Thaumanova Reactor', ar: 33, relics: 11},
  {level: 35, fractal: 'Solid Ocean', ar: 34, relics: 11},
  {level: 36, fractal: 'Uncategorized', ar: 36, relics: 12},
  {level: 37, fractal: 'Snowblind', ar: 38, relics: 12},
  {level: 38, fractal: 'Chaos Isles', ar: 40, relics: 12},
  {level: 39, fractal: 'Molten Furnace', ar: 42, relics: 12},
  {level: 40, fractal: 'Molten Boss', ar: 43, relics: 12},
  {level: 41, fractal: 'Swampland', ar: 45, relics: 13},
  {level: 42, fractal: 'Captain Mai Trin Boss', ar: 47, relics: 13},
  {level: 43, fractal: 'Underground Facility', ar: 49, relics: 13},
  {level: 44, fractal: 'Uncategorized', ar: 50, relics: 13},
  {level: 45, fractal: 'Solid Ocean', ar: 52, relics: 13},
  {level: 46, fractal: 'Volcanic', ar: 54, relics: 14},
  {level: 47, fractal: 'Cliffside', ar: 56, relics: 14},
  {level: 48, fractal: 'Thaumanova Reactor', ar: 58, relics: 14},
  {level: 49, fractal: 'Aetherblade', ar: 59, relics: 14},
  {level: 50, fractal: 'Nightmare', ar: 61, relics: 14},
  {level: 51, fractal: 'Snowblind', ar: 63, relics: 15},
  {level: 52, fractal: 'Volcanic', ar: 65, relics: 15},
  {level: 53, fractal: 'Underground Facility', ar: 67, relics: 15},
  {level: 54, fractal: 'Chaos Isles', ar: 68, relics: 15},
  {level: 55, fractal: 'Thaumanova Reactor', ar: 70, relics: 15},
  {level: 56, fractal: 'Swampland', ar: 72, relics: 15},
  {level: 57, fractal: 'Urban Battleground', ar: 74, relics: 15},
  {level: 58, fractal: 'Molten Furnace', ar: 75, relics: 15},
  {level: 59, fractal: 'Cliffside', ar: 77, relics: 15},
  {level: 60, fractal: 'Solid Ocean', ar: 79, relics: 15},
  {level: 61, fractal: 'Aquatic Ruins', ar: 81, relics: 16},
  {level: 62, fractal: 'Uncategorized', ar: 83, relics: 16},
  {level: 63, fractal: 'Chaos Isles', ar: 84, relics: 16},
  {level: 64, fractal: 'Thaumanova Reactor', ar: 86, relics: 16},
  {level: 65, fractal: 'Aetherblade', ar: 88, relics: 16},
  {level: 66, fractal: 'Urban Battleground', ar: 90, relics: 16},
  {level: 67, fractal: 'Swampland', ar: 91, relics: 16},
  {level: 68, fractal: 'Underground Facility', ar: 93, relics: 16},
  {level: 69, fractal: 'Cliffside', ar: 95, relics: 16},
  {level: 70, fractal: 'Molten Boss', ar: 97, relics: 16},
  {level: 71, fractal: 'Aetherblade', ar: 99, relics: 17},
  {level: 72, fractal: 'Volcanic', ar: 100, relics: 17},
  {level: 73, fractal: 'Captain Mai Trin Boss', ar: 102, relics: 17},
  {level: 74, fractal: 'Snowblind', ar: 104, relics: 17},
  {level: 75, fractal: 'Nightmare', ar: 106, relics: 17},
  {level: 76, fractal: 'Aquatic Ruins', ar: 107, relics: 17},
  {level: 77, fractal: 'Swampland', ar: 109, relics: 17},
  {level: 78, fractal: 'Urban Battleground', ar: 111, relics: 17},
  {level: 79, fractal: 'Uncategorized', ar: 113, relics: 17},
  {level: 80, fractal: 'Solid Ocean', ar: 115, relics: 17},
  {level: 81, fractal: 'Underground Facility', ar: 116, relics: 18},
  {level: 82, fractal: 'Cliffside', ar: 118, relics: 18},
  {level: 83, fractal: 'Molten Furnace', ar: 120, relics: 18},
  {level: 84, fractal: 'Thaumanova Reactor', ar: 122, relics: 18},
  {level: 85, fractal: 'Urban Battleground', ar: 123, relics: 18},
  {level: 86, fractal: 'Snowblind', ar: 125, relics: 18},
  {level: 87, fractal: 'Volcanic', ar: 127, relics: 18},
  {level: 88, fractal: 'Chaos Isles', ar: 129, relics: 18},
  {level: 89, fractal: 'Swampland', ar: 131, relics: 18},
  {level: 90, fractal: 'Molten Boss', ar: 132, relics: 18},
  {level: 91, fractal: 'Uncategorized', ar: 134, relics: 19},
  {level: 92, fractal: 'Volcanic', ar: 136, relics: 19},
  {level: 93, fractal: 'Snowblind', ar: 138, relics: 19},
  {level: 94, fractal: 'Cliffside', ar: 139, relics: 19},
  {level: 95, fractal: 'Underground Facility', ar: 141, relics: 19},
  {level: 96, fractal: 'Aetherblade', ar: 143, relics: 19},
  {level: 97, fractal: 'Thaumanova Reactor', ar: 145, relics: 19},
  {level: 98, fractal: 'Captain Mai Trin Boss', ar: 147, relics: 19},
  {level: 99, fractal: 'Chaos Isles', ar: 148, relics: 19},
  {level: 100, fractal: 'Nightmare', ar: 150, relics: 19}
]
