export default [
  {name: 'Endless Mystery Tonic (beast)', ids: [20319], acquisition: 'Black Lion Chest', permanent: true},
  {name: 'Endless Mystery Tonic (forest)', ids: [20321], acquisition: 'Black Lion Chest', permanent: true},
  {name: 'Endless Mystery Tonic (furniture)', ids: [20320], acquisition: 'Black Lion Chest', permanent: true},
  {name: 'Ice Elemental Tonic', ids: [20338], acquisition: 'Black Lion Chest', permanent: false},
  {name: 'Endless Casual Clothing Tonic', ids: [36187], acquisition: 'Clothing Tonics', permanent: true},
  {name: 'Endless Casual Hoodie Clothing Tonic', ids: [36200], acquisition: 'Clothing Tonics', permanent: true},
  {name: 'Endless Cherry Blossom Clothing Tonic', ids: [36189], acquisition: 'Clothing Tonics', permanent: true},
  {name: 'Endless Common Clothing Tonic', ids: [36179], acquisition: 'Clothing Tonics', permanent: true},
  {name: 'Endless Country Lace Clothing Tonic', ids: [36190], acquisition: 'Clothing Tonics', permanent: true},
  {name: 'Endless Designer Hoodie Clothing Tonic', ids: [36183], acquisition: 'Clothing Tonics', permanent: true},
  {name: 'Endless Dragon Emblem Clothing Tonic', ids: [36192], acquisition: 'Clothing Tonics', permanent: true},
  {name: 'Endless Khaki Clothing Tonic', ids: [36180], acquisition: 'Clothing Tonics', permanent: true},
  {name: 'Endless Layered Vest Clothing Tonic', ids: [36186], acquisition: 'Clothing Tonics', permanent: true},
  {name: 'Endless Leather Hoodie Clothing Tonic', ids: [36184], acquisition: 'Clothing Tonics', permanent: true},
  {name: 'Endless Ornate Clothing Tonic', ids: [36191], acquisition: 'Clothing Tonics', permanent: true},
  {name: 'Endless Riding Clothes Tonic', ids: [36176], acquisition: 'Clothing Tonics', permanent: true},
  {name: 'Endless Silk Brocade Clothing Tonic', ids: [36185], acquisition: 'Clothing Tonics', permanent: true},
  {name: 'Endless Striped Silk Clothing Tonic', ids: [36188], acquisition: 'Clothing Tonics', permanent: true},
  {name: 'Multicolored Ooze Tonic', ids: [36097], acquisition: 'Crafting', permanent: false},
  {name: 'Mystery Tonic (beast)', ids: [20318], acquisition: 'Crafting', permanent: false},
  {name: 'Mystery Tonic (forest)', ids: [20315], acquisition: 'Crafting', permanent: false},
  {name: 'Mystery Tonic (furniture)', ids: [20314], acquisition: 'Crafting', permanent: false},
  {name: 'Potion of Ascalonian Mages', ids: [8700], acquisition: 'Crafting', permanent: false},
  {name: 'Ruminant Tonic', ids: [36115], acquisition: 'Crafting', permanent: false},
  {name: 'Wolf Totem', ids: [72495], acquisition: 'Crafting', permanent: false},
  {name: 'Ghostly Tonic', ids: [8896], acquisition: 'Dungeons', permanent: false},
  {name: 'Knavish Tonic', ids: [8897], acquisition: 'Dungeons', permanent: false},
  {name: 'Overgrown Tonic', ids: [8899], acquisition: 'Dungeons', permanent: false},
  {name: 'Tonic of the Moletariate', ids: [8898], acquisition: 'Dungeons', permanent: false},
  {name: 'Fiery Tonic', ids: [8900], acquisition: 'Dungeons', permanent: false},
  {name: 'Ursan Tonic', ids: [8902], acquisition: 'Dungeons', permanent: false},
  {name: 'Sinister Automatonic', ids: [8903], acquisition: 'Dungeons', permanent: false},
  {name: 'Phantasmal Tonic', ids: [8901], acquisition: 'Dungeons', permanent: false},
  {name: 'Endless Fractal Tonic', ids: [49277], acquisition: 'Fractals', permanent: true},
  {name: 'Endless Fury Combat Tonic', ids: [82000], acquisition: 'Fractals', permanent: true},
  {name: 'Endless Fury Combat Tonic', ids: [81823], acquisition: 'Fractals', permanent: true},
  {name: 'Endless Bottle of Batwing Brew', ids: [67362], acquisition: 'Halloween', permanent: true},
  {name: 'Endless Halloween Tonic', ids: [36106], acquisition: 'Halloween', permanent: true},
  {name: 'Bottle of Batwing Brew', ids: [67379], acquisition: 'Halloween', permanent: false},
  {name: 'Candy Corn Tonic', ids: [36109], acquisition: 'Halloween', permanent: false},
  {name: 'Concentrating Halloween Tonic', ids: [36107], acquisition: 'Halloween', permanent: false},
  {name: 'Halloween Tonic', ids: [36104], acquisition: 'Halloween', permanent: false},
  {name: 'Mummy Tonic', ids: [36114], acquisition: 'Halloween', permanent: false},
  {name: 'Plastic Spider Tonic', ids: [36108], acquisition: 'Halloween', permanent: false},
  {name: 'Spooky Ghost Tonic', ids: [36380], acquisition: 'Halloween', permanent: false},
  {name: 'Spooky Skeleton Tonic', ids: [36382], acquisition: 'Halloween', permanent: false},
  {name: 'Spooky Zombie Tonic', ids: [36381], acquisition: 'Halloween', permanent: false},
  {name: 'Infinite Molten Berserker Tonic', ids: [42403], acquisition: 'Living World', permanent: true},
  {name: 'Infinite Aetherized Tonic', ids: [43352], acquisition: 'Living World', permanent: true},
  {name: 'Infinite Watchknight Tonic', ids: [44720], acquisition: 'Living World', permanent: true},
  {name: 'Infinite Toxic Krait Tonic', ids: [49133], acquisition: 'Living World', permanent: true},
  {name: 'Endless Black Quaggan Tonic', ids: [50046], acquisition: 'Living World', permanent: true},
  {name: 'Endless Blue Quaggan Tonic', ids: [50042], acquisition: 'Living World', permanent: true},
  {name: 'Endless Green Quaggan Tonic', ids: [50047], acquisition: 'Living World', permanent: true},
  {name: 'Endless Pink Quaggan Tonic', ids: [50043], acquisition: 'Living World', permanent: true},
  {name: 'Endless Mystery Quaggan Tonic', ids: [50040], acquisition: 'Living World', permanent: true},
  {name: 'Endless Dolyak Calf Tonic', ids: [66214], acquisition: 'Living World', permanent: true},
  {name: 'Endless Miniature Tonic', ids: [80172], acquisition: 'Living World', permanent: true},
  {name: 'Endless Kodan Tonic', ids: [79849], acquisition: 'Living World', permanent: true},
  {name: 'Endless Embiggening Tonic', ids: [80989], acquisition: 'Living World', permanent: true},
  {name: 'Black Quaggan Tonic', ids: [50045], acquisition: 'Living World', permanent: false},
  {name: 'Blue Quaggan Tonic', ids: [50038], acquisition: 'Living World', permanent: false},
  {name: 'Green Quaggan Tonic', ids: [50044], acquisition: 'Living World', permanent: false},
  {name: 'Pink Quaggan Tonic', ids: [50039], acquisition: 'Living World', permanent: false},
  {name: 'Endless Arid Devourer Tonic', ids: [67783, 67805], acquisition: 'Random Drop', permanent: true},
  {name: 'Endless Mordrem Teragriff Tonic', ids: [68512, 68530], acquisition: 'Random Drop', permanent: true},
  {name: 'Endless Charged Potion', ids: [35749], acquisition: 'Lost Orrian Jewelry Box', permanent: true},
  {name: 'Endless Cold Potion', ids: [35747], acquisition: 'Lost Orrian Jewelry Box', permanent: true},
  {name: 'Endless Hard Potion', ids: [35748], acquisition: 'Lost Orrian Jewelry Box', permanent: true},
  {name: 'Endless Warm Potion', ids: [35750], acquisition: 'Lost Orrian Jewelry Box', permanent: true},
  {name: 'Charged Potion', ids: [35746], acquisition: 'Lost Orrian Jewelry Box', permanent: false},
  {name: 'Cold Potion', ids: [35744], acquisition: 'Lost Orrian Jewelry Box', permanent: false},
  {name: 'Hard Potion', ids: [35745], acquisition: 'Lost Orrian Jewelry Box', permanent: false},
  {name: 'Warm Potion', ids: [35743], acquisition: 'Lost Orrian Jewelry Box', permanent: false},
  {name: 'Endless Mushroom Emperor Tonic', ids: [71680], acquisition: 'Mystic Forge', permanent: true},
  {name: 'Endless Gargoyle Tonic', ids: [79650], acquisition: 'Mystic Forge', permanent: true},
  {name: 'Endless Hellfire Skeleton Tonic', ids: [79668], acquisition: 'Mystic Forge', permanent: true},
  {name: 'Endless Ignited Wraith Tonic', ids: [79664], acquisition: 'Mystic Forge', permanent: true},
  {name: 'Endless Shadow Raven Tonic', ids: [79657], acquisition: 'Mystic Forge', permanent: true},
  {name: 'Blue Moa Tonic', ids: [20333], acquisition: 'Mystic Forge', permanent: false},
  {name: 'Boar Tonic', ids: [20347], acquisition: 'Mystic Forge', permanent: false},
  {name: 'Devourer Tonic', ids: [20348], acquisition: 'Mystic Forge', permanent: false},
  {name: 'Eagle Raptor Tonic', ids: [20341], acquisition: 'Mystic Forge', permanent: false},
  {name: 'Eagle Tonic', ids: [20327], acquisition: 'Mystic Forge', permanent: false},
  {name: 'Floater Tonic', ids: [20353], acquisition: 'Mystic Forge', permanent: false},
  {name: 'Imp Tonic', ids: [20340], acquisition: 'Mystic Forge', permanent: false},
  {name: 'Jackalope Tonic', ids: [20330], acquisition: 'Mystic Forge', permanent: false},
  {name: 'Krait Tonic', ids: [20343], acquisition: 'Mystic Forge', permanent: false},
  {name: 'Leopard Tonic', ids: [20331], acquisition: 'Mystic Forge', permanent: false},
  {name: 'Minotaur Tonic', ids: [20332], acquisition: 'Mystic Forge', permanent: false},
  {name: 'Ooze Tonic', ids: [20350], acquisition: 'Mystic Forge', permanent: false},
  {name: 'Owl Tonic', ids: [20328], acquisition: 'Mystic Forge', permanent: false},
  {name: 'Pig Tonic', ids: [20335], acquisition: 'Mystic Forge', permanent: false},
  {name: 'Pink Moa Tonic', ids: [20334], acquisition: 'Mystic Forge', permanent: false},
  {name: 'Plant Wolf Tonic', ids: [20336], acquisition: 'Mystic Forge', permanent: false},
  {name: 'Ram Tonic', ids: [20344], acquisition: 'Mystic Forge', permanent: false},
  {name: 'Skale Tonic', ids: [20351], acquisition: 'Mystic Forge', permanent: false},
  {name: 'Skritt Tonic', ids: [20339], acquisition: 'Mystic Forge', permanent: false},
  {name: 'Snow Owl Tonic', ids: [20322], acquisition: 'Mystic Forge', permanent: false},
  {name: 'Spider Tonic', ids: [20352], acquisition: 'Mystic Forge', permanent: false},
  {name: 'Stag Tonic', ids: [20346], acquisition: 'Mystic Forge', permanent: false},
  {name: 'Steam Ogre Tonic', ids: [20354], acquisition: 'Mystic Forge', permanent: false},
  {name: 'Wolf Tonic', ids: [20337], acquisition: 'Mystic Forge', permanent: false},
  {name: 'Endless Dust Mite Tonic', ids: [67784], acquisition: 'NPC Purchase', permanent: true},
  {name: 'Endless Mordrem Husk Tonic', ids: [68058], acquisition: 'NPC Purchase', permanent: true},
  {name: 'Endless Mordrem Troll Tonic', ids: [68520], acquisition: 'NPC Purchase', permanent: true},
  {name: 'Endless Exalted Caster Tonic', ids: [76174], acquisition: 'NPC Purchase', permanent: true},
  {name: 'Endless Guild Banner Tonic', ids: [39711], acquisition: 'NPC Purchase', permanent: true},
  {name: 'Endless Beetle Tonic', ids: [73577], acquisition: 'NPC Purchase', permanent: true},
  {name: 'Endless Mystery Cat Tonic', ids: [39101], acquisition: 'NPC Purchase', permanent: true},
  {name: 'Infinite Slubling Tonic', ids: [77983], acquisition: 'NPC Purchase', permanent: true},
  {name: 'Endless Nuhoch Tonic', ids: [77101], acquisition: 'NPC Purchase', permanent: true},
  {name: 'Endless Jade Construct Tonic', ids: [79583], acquisition: 'NPC Purchase', permanent: true},
  {name: 'Endless Spotted Beetle Tonic', ids: [74186], acquisition: 'NPC Purchase', permanent: true},
  {name: 'Dolyak Tincture', ids: [8671], acquisition: 'NPC Purchase', permanent: false},
  {name: 'Essence of Jellyfish', ids: [8755], acquisition: 'NPC Purchase', permanent: false},
  {name: 'Hazmat Suit Transformation Tonic', ids: [8718], acquisition: 'NPC Purchase', permanent: false},
  {name: 'Murellow Tonic', ids: [8670], acquisition: 'NPC Purchase', permanent: false},
  {name: 'Potion of Jackalope Transformation', ids: [8644], acquisition: 'NPC Purchase', permanent: false},
  {name: 'Quaggan Tonic', ids: [8729], acquisition: 'NPC Purchase', permanent: false},
  {name: 'Potion of Young Karka Transformation', ids: [36725], acquisition: 'NPC Purchase', permanent: false},
  {name: 'Ghost Owl Feather', ids: [8639], acquisition: 'NPC Purchase', permanent: false},
  {name: 'Grawl Snowman Potion', ids: [8640], acquisition: 'NPC Purchase', permanent: false},
  {name: 'Matlal Enchanted Pig Truffle', ids: [8748], acquisition: 'NPC Purchase', permanent: false},
  {name: 'Plant Dog Transformation', ids: [8750], acquisition: 'NPC Purchase', permanent: false},
  {name: 'Potion of Ettin Essence', ids: [8656], acquisition: 'NPC Purchase', permanent: false},
  {name: 'Potion of Hylek Transformation', ids: [8776], acquisition: 'NPC Purchase', permanent: false},
  {name: 'Guild Banner Tonic', ids: [39696], acquisition: 'NPC Purchase', permanent: false},
  {name: 'Endless Interface Crafter Golem Tonic', ids: [69651], acquisition: 'Overwolf App Challenge', permanent: true},
  {name: 'Endless Karka Tonic', ids: [36727], acquisition: 'Princess Loot Bag', permanent: true},
  {name: 'Karka Tonic', ids: [36726], acquisition: 'Princess Loot Bag', permanent: false},
  {name: 'Endless Monkey King Tonic', ids: [66768, 66926], acquisition: 'Random Drop', permanent: true},
  {name: 'Endless Mordrem Thrasher Tonic', ids: [68064, 68065], acquisition: 'Random Drop', permanent: true},
  {name: 'Endless Mushroom King Tonic', ids: [71739, 73677], acquisition: 'Random Drop', permanent: true},
  {name: 'Endless Mushroom Queen Tonic', ids: [72072, 73310], acquisition: 'Random Drop', permanent: true},
  {name: 'Endless Mushroom Tonic', ids: [75214, 75636], acquisition: 'Random Drop', permanent: true},
  {name: 'Endless Skritt Burglar Tonic', ids: [68046], acquisition: 'Random Drop', permanent: true},
  {name: 'Endless Exalted Bastion Tonic', ids: [70619, 73150], acquisition: 'Random Drop', permanent: true},
  {name: 'Endless Chak Drone Tonic', ids: [72894, 73663], acquisition: 'Random Drop', permanent: true},
  {name: 'Endless Chak Slinger Tonic', ids: [71683, 75615], acquisition: 'Random Drop', permanent: true},
  {name: 'Endless Chak Zapper Tonic', ids: [72203, 74594], acquisition: 'Random Drop', permanent: true},
  {name: 'Endless Ley-Line Anomaly Tonic', ids: [79034, 79042], acquisition: 'Random Drop', permanent: true},
  {name: 'Endless Nuhoch Crusher Tonic', ids: [73194, 77167], acquisition: 'Random Drop', permanent: true},
  {name: 'Endless Multicolored Ooze Tonic', ids: [36105], acquisition: 'Unknown', permanent: true},
  {name: 'Endless Chugger Tonic', ids: [], acquisition: 'Unknown', permanent: true},
  {name: 'Enchanted Snowball', ids: [77568], acquisition: 'Wintersday', permanent: true},
  {name: 'Endless Gift Box Tonic', ids: [68368], acquisition: 'Wintersday', permanent: true},
  {name: 'Endless Gift Dolyak Tonic', ids: [38121], acquisition: 'Wintersday', permanent: true},
  {name: 'Endless Toymaker\'s Tonic', ids: [38115], acquisition: 'Wintersday', permanent: true},
  {name: 'Endless Plush Griffon Tonic', ids: [38117], acquisition: 'Wintersday', permanent: true},
  {name: 'Endless Princess Doll Tonic', ids: [38120], acquisition: 'Wintersday', permanent: true},
  {name: 'Endless Toy Golem Tonic', ids: [38118], acquisition: 'Wintersday', permanent: true},
  {name: 'Endless Toy Soldier Tonic', ids: [38119], acquisition: 'Wintersday', permanent: true},
  {name: 'Endless Toy Ventari Tonic', ids: [38116], acquisition: 'Wintersday', permanent: true},
  {name: 'Gift Dolyak Tonic', ids: [38125], acquisition: 'Wintersday', permanent: false},
  {name: 'Festive Golem Tonic', ids: [38062], acquisition: 'Wintersday', permanent: false},
  {name: 'Plush Griffon Tonic', ids: [38127], acquisition: 'Wintersday', permanent: false},
  {name: 'Princess Doll Tonic', ids: [38124], acquisition: 'Wintersday', permanent: false},
  {name: 'Reindeer Tonic', ids: [38063], acquisition: 'Wintersday', permanent: false},
  {name: 'Snowman Tonic', ids: [38061], acquisition: 'Wintersday', permanent: false},
  {name: 'Toy Golem Tonic', ids: [38126], acquisition: 'Wintersday', permanent: false},
  {name: 'Toy Soldier Tonic', ids: [38123], acquisition: 'Wintersday', permanent: false},
  {name: 'Toy Ventari Tonic', ids: [38122], acquisition: 'Wintersday', permanent: false}
]
